import type { Metadata } from 'next';
import { Roboto } from 'next/font/google';
import './globals.css';
import Nav from './componentes/Nav/Nav';

const roboto = Roboto({
  weight: ['400', '700'],
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Pokedex',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={`${roboto.className} bg-red-50`}>
        <Nav />
        {children}
      </body>
    </html>
  );
}
